name: 'Match PR Label'
description: 'Requires a PR to exactly one of the labels from a list'
inputs:
  allowed:
    description: 'comma- or newline-separated label names to look for'
    required: true
outputs:
  match:
    description: 'The matched label, if found'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'hash'
  color: 'orange'
